title: Heena Jain
logo: assets/img/0FE29F1A-7501-40D6-AD8C-88C34A781810.JPG
description: I am working as an Automation Tester and persuing Executive PG Programme in Machine Learning & AI from IITB
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
